Replace EMAIL_REGEX with email-validator package
VandyHacks/vaken pull request #747
Opened 2020-11-29 12:42 UTC by siraben

Rebased on latest master.

2020-12-05 14:57 UTC, leonm1 requested changes

2020-12-05 14:57 UTC, leonm1 commented on src/client/routes/manage/CreateSponsor.tsx
> +import * as EmailValidator from 'email-validator';
This should go on line 3. I believe the import sorter will put it in the right place if you eliminate the whitespace on line 17.

2020-12-13 21:20 UTC, leonm1 approved these changes

2020-12-13 21:20 UTC, leonm1 commented
Thanks for the PR!

2020-12-30 05:06 UTC, siraben commented
@bencooper222 was it redundant?

2020-12-30 05:39 UTC, siraben commented
Rebased on master

2020-12-30 06:16 UTC, bencooper222 approved these changes
lgtm

2020-12-30 12:12 UTC, merged

2020-12-31 09:25 UTC, aadibajpai commented
@siraben it should be used here as well https://github.com/VandyHacks/vaken/blob/main/scripts/makeOrganizer.ts#L5 I guess

2020-12-31 09:28 UTC, siraben commented
Thanks, will look into this.

2020-12-31 09:32 UTC, aadibajpai commented
> Thanks, will look into this.

in fact, https://github.com/VandyHacks/vaken/search?q=EMAIL_REGEX

2020-12-31 09:34 UTC, siraben commented
😱 DESTROY ALL THE EMAIL REGEX